### ISSUE TITLE
does the plugin work with backstage 1.13.0?

### ISSUE THREAD

**Issue by wanisfahmyDE** [StatusNeo/backstage-plugin-github#11]
Hello @NishkarshRaj ,

We tried installing the plugin and including it in the HomePage.tsx (we already use the Github provider beforehand)
the widgets appear in the home page but they're empty and upon pressing login in them nothing happens and no error is thrown in the browser.

Also tried to add them in the GroupEntityPage but this seems conflict with Spotify's Shortcut plugin and crashes immediately.

Any hints what might be wrong?

Thanks

**Comment by Abhay-soni-developer** [comment]
@wanisfahmyDE I would love to connect with you over this, to resolve this issue
let us schedule a online meet 
where you can reproduce the error for me so i can get a better understanding

**Comment by wanisfahmyDE** [comment]
thanks @Abhay-soni-developer i'll send you an invite on your mail in your profile

**Comment by Abhay-soni-developer** [comment]
Hello Wanis,

After today's collaboration, I went through the codebase and setup process.
and finally figured out why it was not working for you. There was a bug too, which I have fixed
My team will be releasing the new version by tomorrow.  (v0.2.2)
please go through the setup process again as there are some changes and one missing step too which I have added now.

Regards 
Abhay soni

**Comment by Abhay-soni-developer** [comment]
please let us know, if it is working for you now as we can succesfully close this issue

**Comment by wanisfahmyDE** [comment]
Hi @Abhay-soni-developer now it works as expected.
Thanks for your effort and fast response
closing issue
